package db;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;

public class DatabaseInitializer {
    private static final Logger logger = LoggerFactory.getLogger(DatabaseInitializer.class);

    public static void initTable() {
        try (Connection conn = ConnectionManager.getConnection();
             Statement stmt = conn.createStatement()) {

            // 1. User 테이블 생성
            String userSql = "CREATE TABLE IF NOT EXISTS users (" +
                    "userId VARCHAR(255) PRIMARY KEY, " +
                    "password VARCHAR(255) NOT NULL, " +
                    "name VARCHAR(255) NOT NULL, " +
                    "email VARCHAR(255))";
            stmt.execute(userSql);

            // 2. Article 테이블 생성
            String articleSql = "CREATE TABLE IF NOT EXISTS articles (" +
                    "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                    "writerId VARCHAR(255) NOT NULL, " + // 작성자 확인용
                    "content TEXT NOT NULL, " +          // 글 본문
                    "imagePath VARCHAR(500), " +         // 업로드한 이미지 경로
                    "createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP, " +
                    "CONSTRAINT fk_writer FOREIGN KEY (writerId) REFERENCES users(userId) " +
                    "ON DELETE CASCADE ON UPDATE CASCADE)";
            stmt.execute(articleSql);

            logger.info("Database tables initialized successfully.");

        } catch (SQLException e) {
            logger.error("Failed to initialize database tables", e);
            throw new RuntimeException(e);
        }
    }
}